site_name: Yufan Zhang
theme:
  name: material
  font: 
    text: Ubuntu
  logo: assets/logo5.png
  favicon: assets/logo5.png
  features:
  - navigation.tabs
  - toc.integrate
nav:
  - 'About Me': 'index.md'
  - 'Past Experience': 'Past Experience.md'
  - 'Future Ambition': 'Future Ambition.md'
markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css